site_name: IRM de diffusion
site_description: Synthèse opérationnelle des bonnes pratiques en IRM de diffusion.
theme:
  name: material
  logo: assets/images/site/logo_remi.png
  favicon: assets/images/site/logo_remi.png
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  language: fr
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
nav:
  - Accueil: index.md
  - Acquisition:
    - Introduction: acquisition/index.md
    - Description: acquisition/01-description.md
    - Analyse DTI: acquisition/02-pour-une-bonne-analyse-dti.md
    - Tractographie: acquisition/03-pour-une-bonne-tractographie.md
    - DKI: acquisition/04-pour-du-dki.md
    - NODDI: acquisition/05-pour-du-noddi.md
    - Acquisition détaillée: acquisition/06-acquisition.md
    - Traitement de données: acquisition/07-traitement-de-donnees.md
  - Traitement:
    - Introduction: analyses/index.md
    - Préparation BIDS: analyses/01-preparation-bids.md
    - Contrôle qualité: analyses/02-controle-qualite.md
    - Prétraitements: analyses/03-pretraitements.md
    - Modélisations: analyses/04-modelisations.md
    - Tractographie: analyses/05-tractographie.md
    - Analyses voxel-wise: analyses/06-analyses-voxel-wise.md
  - Tutoriel:
    - Introduction: tutorial/index.md
    - Notebooks: tutorial/notebooks/README.md
  - Contributeur: contributeur.md
